=== farihashafiqwork-dev/APTECH_DISM/2.XML&JSON/XML/1.DTD/BATCH.dtd
<!ELEMENT BATCH (S)*>
  <!ELEMENT S (ID,Name,Sem,Marks)>
  <!ELEMENT ID (#PCDATA)> 
  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Sem (#PCDATA)>
  <!ELEMENT Marks (#PCDATA)>
  <!ATTLIST Marks Remarks CDATA #IMPLIED>

=== farihashafiqwork-dev/APTECH_DISM/2.XML&JSON/XML/1.DTD/batch.xml
<?xml version="1.0" encoding="UTF-8" standalone = "no" ?>
<!DOCTYPE Batch SYSTEM "BATCH.dtd">
<BATCH>
<S>
    	<ID> 12345</ID>
    	<Name>HAMZA</Name>
	<SEM> DISM </SEM>
	<Marks remarks="Good"> 100 </Marks>
  </S>
<S>
    	<ID> 12345</ID>
    	<Name>HAMZA</Name>
	<SEM> DISM </SEM>
	<Marks remarks="Good"> 100 </Marks>
  </S>
</BATCH>
